[SBS-2][SBS-12]ui: product detail screen
superbadteam/superbad-store_mobile pull request #10
Opened 2024-05-08 11:30 UTC by duchuyyyy

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

#Screenshot 
![Screenshot from 2024-05-08 18-25-27](https://github.com/superbadteam/superbad-store_mobile/assets/95920128/5df22d39-34e6-4b8f-ab57-13c1f04eb6f3)

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-08 16:47 UTC, phamhongphuc1403 requested changes
chưa chạy yant lint để format code

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/components/SlideShow.tsx
> +const styles = StyleSheet.create({
theo style naming convention mấy screen khác

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/components/SlideShow.tsx
> +      <Swiper style={styles.wrapper} showsButtons={false} autoplay>
`showsButtons={false} autoplay` có nên fix cứng như vậy không?

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/components/SlideShow.tsx
> +  wrapper: {},
không dùng thì xoá đi

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +        </View>
Bỏ ra component riêng

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  orange: "orange",
đã có file config color rồi

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  const [selectedSize, setSelectedSize] = useState("");
define type cho selectedSize luôn

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +            <Text style={[{ color: colors.gray }, styles.countReview]}>87 Reviews</Text>
dùng translation

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +            <Text style={[styles.price, styles.text, { color: colors.text }]}>Size</Text>
dùng translation

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +            <Text style={{ color: colors.text }}>Size Chart</Text>
dùng translation

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +              onPress={() => setSelectedSize(size)}
chưa có useEffect đổi màu selected size hả?

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +              style={[styles.sizeButton, selectedSize === size ? styles.selectedSizeButton : null]}
selectedSize === size ? styles.selectedSizeButton : null
này có đổi màu dynamically không vậy?

2024-05-08 16:47 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +          <Text style={[styles.buttonText, { color: colors.blue }]}>Add to Cart</Text>
sửa lại dùng translation hết đi

2024-05-10 14:07 UTC, duchuyyyy commented on app/components/SlideShow.tsx
> +      <Swiper style={styles.wrapper} showsButtons={false} autoplay>
![image](https://github.com/superbadteam/superbad-store_mobile/assets/95920128/2935cb04-a2c6-44f4-921d-f6de654fee9c)
fix cứng để ẩn 2 cái dấu mũi tên trong slidéhơ đi cho giống UI

2024-05-10 14:07 UTC, duchuyyyy commented on app/components/SlideShow.tsx
> +  wrapper: {},
OK

2024-05-10 14:09 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +        </View>
Cái này thanh header riêng của màn hình Product Detail mà tách ra làm gì

2024-05-10 15:17 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  const [selectedSize, setSelectedSize] = useState("");
cái này họ chọn mới hiện lên chớ

2024-05-11 12:16 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +        </View>
sao k làm chung?

2024-05-11 12:16 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  const [selectedSize, setSelectedSize] = useState("");
interface

2024-05-11 12:17 UTC, phamhongphuc1403 commented on app/components/SlideShow.tsx
> +      <Swiper style={styles.wrapper} showsButtons={false} autoplay>
lỡ chỗ khác cần dùng thì sao?

2024-05-11 12:21 UTC, duchuyyyy commented on app/components/SlideShow.tsx
> +      <Swiper style={styles.wrapper} showsButtons={false} autoplay>
Thì css đè lên thôi m

2024-05-12 05:22 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  orange: "orange",
DONE

2024-05-12 06:21 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  const [selectedSize, setSelectedSize] = useState("");
DONE

2024-05-16 06:01 UTC, phamhongphuc1403 commented on app/theme/colors.ts
> +  orange: "orange",
m có biết "palette" là gì không mà không bỏ vào đó?

2024-05-16 06:02 UTC, phamhongphuc1403 commented on package.json
> +      ],
sao lại edit mấy dòng này vậy?

2024-05-16 06:04 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  const [selectedSize, setSelectedSize] = useState<number>(-1);
đổi lại thành type đi, app mình không support size

2024-05-16 06:04 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +              <Text style={[$reviewText, { color: colors.white }]}>4.1</Text>
tx?

2024-05-16 06:05 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  fontSize: 18,
sao vẫn set font size ở đây vậy?

2024-05-16 06:49 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +              <Text style={[$reviewText, { color: colors.white }]}>4.1</Text>
Số này sau sẽ call api m

2024-05-16 06:50 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  const [selectedSize, setSelectedSize] = useState<number>(-1);
DONE

2024-05-16 06:50 UTC, duchuyyyy commented on package.json
> +      ],
DONE

2024-05-16 06:51 UTC, duchuyyyy commented on app/theme/colors.ts
> +  orange: "orange",
Đã đổi lại thành white

2024-05-17 07:19 UTC, huynamboz approved these changes
May LGTM

2024-05-17 11:00 UTC, le-anh-dung-05-05 approved these changes

2024-05-17 11:11 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  fontSize: 18,
DONE

2024-05-17 15:49 UTC, phamhongphuc1403 commented on app/theme/colors.ts
> +  orange: "orange",
còn mấy cái khác thì sao

2024-05-17 15:50 UTC, phamhongphuc1403 commented on app/theme/colors.ts
> +  orange: "orange",
pallete là bảng màu mà

2024-05-17 15:50 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +  fontSize: 18,
done đâu?

2024-05-17 15:56 UTC, phamhongphuc1403 commented on app/navigators/DemoNavigator.tsx
> +          tabBarLabel: "product detail",
này để làm gì m

2024-05-17 16:31 UTC, phdhuy commented on app/navigators/DemoNavigator.tsx
> +          tabBarLabel: "product detail",
Cái ni để nó thêm một tab bên navigation bar để check UI m

2024-05-17 16:40 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +        </View>
Đã tách ra task riêng

2024-05-17 17:34 UTC, duchuyyyy commented on app/theme/colors.ts
> +  orange: "orange",
Đã đổi sang palette

2024-05-17 17:54 UTC, phamhongphuc1403 commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +              <Ionicons name="star" size={20} color="white" />{" "}
{" "}  la gi m

2024-05-17 18:20 UTC, duchuyyyy commented on app/screens/ProductDetailScreen/ProductDetailScreen.tsx
> +              <Ionicons name="star" size={20} color="white" />{" "}
Da xoa

2024-05-17 18:21 UTC, phamhongphuc1403 approved these changes

2024-05-17 18:21 UTC, huynamboz approved these changes
LGTM

2024-05-17 18:26 UTC, merged