[SBS-2][SBS-17] UI : Cart Screen
superbadteam/superbad-store_mobile pull request #11
Opened 2024-05-10 15:45 UTC by le-anh-dung-05-05

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
![1ef8981e-ce0c-45cd-95d3-6dd00c93e45c](https://github.com/superbadteam/superbad-store_mobile/assets/95488550/f7788ed2-f683-4a13-8d47-f3469acac938)
![50b1513d-a5e5-4e37-b750-342ccaf250a2](https://github.com/superbadteam/superbad-store_mobile/assets/95488550/d5a17283-268d-4638-a7f0-fd64eda6fb98)

2024-05-11 12:54 UTC, phamhongphuc1403 requested changes
component convention đang để tất cả vào chung 1 folder mà, sao chia sub folder vậy

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/components/CartItem/CartItem.tsx
> +  updateTotalPrice: (price: number,quantityChange:number) => void;
chưa chạy yarn lint à?

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/components/CartItem/CartItem.tsx
> +    ]);
có cách nào để dùng translation cho cái này không?

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/components/CartItem/CartItem.tsx
> +        style: "cancel",
cancel thì không cần onpress hả?

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/components/CartItem/CartItem.tsx
> +      <View style={$itemInformations}>
information không đếm được

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/components/CartItem/CartItem.tsx
> +        <TouchableOpacity onPress={handleDeletePress} style={$iconContainer}>
test là remove mà tên hàm là delete à m

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/components/CartItem/CartItem.tsx
> +  fontSize: 16,
check trong Component mấy cái nào ngta define prop sẵn rồi thì đừng bỏ vào style

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/components/Screen/Screen.tsx
> +});
này để làm gì m?

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +              text={"Price Detail (" + `${clothItems.length}` + " items)"}
sao không dùng tx vậy?

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +        <View style={$sumaryCard}>
sai chính tả

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +        {clothItems.slice(0, 7).map((item) => (
tại vì sao phải slice(0, 7) vậy

2024-05-11 12:54 UTC, phamhongphuc1403 commented on app/theme/colors.ts
> +  gray_100: "#F3F4F6",
này phải để ở palette chứ

2024-05-11 12:54 UTC, phamhongphuc1403 requested changes
component convention đang để tất cả vào chung 1 folder mà, sao chia sub folder vậy

2024-05-11 12:56 UTC, le-anh-dung-05-05 commented
Update code theo convention 
Calculate tổng giá trong cart
Xóa ảnh tải về, đổi image thành link ảnh

2024-05-17 16:59 UTC, leanhdung0505 commented on app/components/Screen/Screen.tsx
> +});
Cái đó thừa mà t quên xóa

2024-05-17 16:59 UTC, leanhdung0505 commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +        {clothItems.slice(0, 7).map((item) => (
Vì chưa xử lý add to cart , nên t lấy 8 items đầu trong data

2024-05-17 16:59 UTC, leanhdung0505 commented on app/components/CartItem/CartItem.tsx
> +        style: "cancel",
không cần

2024-05-17 16:59 UTC, leanhdung0505 commented on app/components/CartItem/CartItem.tsx
> +    ]);
T nghĩ translation chỉ dùng trong các thẻ nên t chưa tìm hiểu

2024-05-17 16:59 UTC, leanhdung0505 commented on app/components/CartItem/CartItem.tsx
> +        <TouchableOpacity onPress={handleDeletePress} style={$iconContainer}>
Done

2024-05-17 16:59 UTC, leanhdung0505 commented on app/components/CartItem/CartItem.tsx
> +      <View style={$itemInformations}>
Done

2024-05-17 16:59 UTC, leanhdung0505 commented on app/components/CartItem/CartItem.tsx
> +  fontSize: 16,
Done

2024-05-17 16:59 UTC, leanhdung0505 commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +        <View style={$sumaryCard}>
Done

2024-05-17 16:59 UTC, leanhdung0505 commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +        {clothItems.slice(0, 7).map((item) => (
Done

2024-05-17 16:59 UTC, leanhdung0505 commented on app/theme/colors.ts
> +  gray_100: "#F3F4F6",
Done

2024-05-17 18:22 UTC, phamhongphuc1403 commented on app/components/CartItem/CartItem.tsx
> +    ]);
thì tìm hiểu đi

2024-05-17 18:23 UTC, phamhongphuc1403 commented on app/i18n/en.ts
> +    title: "My Cart",
sao lại sửa cái này

2024-05-18 16:04 UTC, phamhongphuc1403 commented on app/theme/colors.ts
> +  gray_100: "#F3F4F6",
convention đâu có _ ở giữa đâu

2024-05-18 17:41 UTC, LeTatTuan commented on app/navigators/DemoNavigator.tsx
> +      />
Test xong nhớ để lại cái cũ, đỡ conflict.

2024-05-18 17:44 UTC, LeTatTuan commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +import { Button, Screen } from "../../components";
import thư mục qua file index.ts được mà, tạo component mới thì bỏ vào index.ts.

2024-05-19 03:05 UTC, le-anh-dung-05-05 commented
Đã fix bug tính tổng khi change số lượng

2024-05-19 03:25 UTC, le-anh-dung-05-05 commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +import { Button, Screen } from "../../components";
Done

2024-05-19 03:25 UTC, le-anh-dung-05-05 commented on app/navigators/DemoNavigator.tsx
> +      />
Done

2024-06-07 03:14 UTC, le-anh-dung-05-05 commented on app/i18n/en.ts
> +    title: "My Cart",
Done

2024-06-07 03:20 UTC, le-anh-dung-05-05 commented on app/theme/colors.ts
> +  gray_100: "#F3F4F6",
Done

2024-06-07 04:03 UTC, le-anh-dung-05-05 commented on app/screens/DemoCartScreen/DemoCartScreen.tsx
> +              text={"Price Detail (" + `${clothItems.length}` + " items)"}
Done

2024-06-07 05:26 UTC, spartan-longnguyen commented
> Đã fix bug tính tổng khi change số lượng Khi giảm xuống 0 thì sẽ hiện thông báo remove

có ai hỏi không Dũng ?

2024-06-07 06:44 UTC, le-anh-dung-05-05 commented on app/components/CartItem/CartItem.tsx
> +    ]);
Done

2024-06-07 06:49 UTC, phamhongphuc1403 commented on app/components/CartItem.tsx
> +          <Text text={`$${item.price * quantity}`} style={$textMedium} preset="bold" />
trx

2024-06-07 07:25 UTC, le-anh-dung-05-05 commented on app/components/CartItem.tsx
> +          <Text text={`$${item.price * quantity}`} style={$textMedium} preset="bold" />
Done

2024-06-07 07:28 UTC, phamhongphuc1403 approved these changes

2024-06-07 07:30 UTC, huynamboz approved these changes
LGTM

2024-06-07 07:30 UTC, merged