[SBS-11] ui: update home page screen
superbadteam/superbad-store_mobile pull request #14
Opened 2024-05-17 18:07 UTC by trungdong11

# Description
    List category
    Recommend screen

#Screen
![328738691-a9715b82-fd6d-4c4f-97dd-718c33e62657](https://github.com/superbadteam/superbad-store_mobile/assets/89646192/fa5cac1e-0a7f-4979-87b8-e2986347a29b)

2024-05-17 18:19 UTC, phamhongphuc1403 requested changes

2024-05-17 18:19 UTC, phamhongphuc1403 commented on app/screens/DemoCommunityScreen.tsx
để nguyên file này đi

2024-05-17 18:19 UTC, phamhongphuc1403 commented on app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
tạo screen mới r bỏ vào navigation

2024-05-18 14:06 UTC, trungdong11 commented on app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
done

2024-05-18 14:06 UTC, trungdong11 commented on app/screens/DemoCommunityScreen.tsx
done

2024-05-18 15:42 UTC, huynamboz commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +                <TextInput
răn k dùng TextField

2024-05-18 15:58 UTC, phamhongphuc1403 commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +          const response = await api.getCategories();
dung swr

2024-05-18 15:59 UTC, phamhongphuc1403 commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +                    <Text>View All</Text>
tx

2024-05-18 16:00 UTC, phamhongphuc1403 commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +  fontSize: 16,
bỏ lên prop

2024-05-19 02:33 UTC, trungdong11 commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +                <TextInput
Vì sao phải dùng textField mi, phải css nhiều hơn

2024-05-19 03:24 UTC, trungdong11 commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +  fontSize: 16,
done

2024-05-19 03:24 UTC, trungdong11 commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +                    <Text>View All</Text>
done

2024-05-19 03:48 UTC, huynamboz commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +                      <View style={{flexDirection: "row", gap: 6, alignItems: "center"}}>
fix mấy cái css inline này đi m

2024-05-19 04:02 UTC, trungdong11 commented on app/screens/DemoHomePageScreen/DemoHomePageScreen.tsx
> +                      <View style={{flexDirection: "row", gap: 6, alignItems: "center"}}>
đã fix

2024-05-19 04:09 UTC, huynamboz approved these changes

2024-05-19 05:35 UTC, phamhongphuc1403 approved these changes

2024-05-19 05:38 UTC, merged