[SBS-13][SBS-24] feat: integrate create product api
superbadteam/superbad-store_mobile pull request #17
Opened 2024-05-19 05:06 UTC by huynamboz

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-19 18:09 UTC, phdhuy commented on app/components/CreateProduct/SelectImageGroup.tsx
>      const newItems = itemType.filter((item) => item.id !== id);
Sao khai báo id của itemType ở trên là uuid mà xuống đây lại là string vậy @huynamboz

2024-05-19 18:12 UTC, huynamboz commented on app/components/CreateProduct/SelectImageGroup.tsx
>      const newItems = itemType.filter((item) => item.id !== id);
type là string m, ở trên là initial value

2024-05-19 18:14 UTC, huynamboz commented on app/components/CreateProduct/SelectImageGroup.tsx
>      const newItems = itemType.filter((item) => item.id !== id);
typescript không có buildin type uuid

2024-05-19 18:21 UTC, duchuyyyy commented on app/components/CreateProduct/SelectImageGroup.tsx
>      const newItems = itemType.filter((item) => item.id !== id);
uhm ok

2024-05-19 18:27 UTC, duchuyyyy approved these changes
T thấy ok r m @huynamboz

2024-05-19 18:56 UTC, phamhongphuc1403 requested changes

2024-05-19 18:56 UTC, phamhongphuc1403 commented on app/components/CreateProduct/SelectImageGroup.tsx
> +const { v4 } = require("uuid");
sao không import

2024-05-19 18:56 UTC, phamhongphuc1403 commented on app/screens/DemoCreateProductScreen.tsx
> +        });
nên dùng hook không m?

2024-05-19 18:56 UTC, phamhongphuc1403 commented on app/services/hooks/useInventory.tsx
> +  const { trigger: getCategories, isMutating } = useSWRMutation(
useSWR thôi m, useSWRMutation không phải dùng trong trường hợp này, đọc doc đi m

2024-05-19 18:56 UTC, phamhongphuc1403 commented on app/screens/DemoCreateProductScreen.tsx
>            console.error("Error fetching categories:", error);
sao lại try catch nữa m

2024-05-19 18:56 UTC, phamhongphuc1403 commented on app/services/module/shared.ts
> +import { api } from "../api";
sao folder module mà không phải modules m?

2024-05-19 19:25 UTC, LeTatTuan commented on app/components/Dropdown.tsx
>            <AntDesign style={$icon} color={isFocus ? "blue" : "black"} name="Safety" size={20} />
Nên dùng colors.palette

2024-05-19 19:44 UTC, LeTatTuan commented on app/screens/DemoCreateProductScreen.tsx
> +              }}
- Mấy chỗ ...product: sao chép nhiều nơi
- Nếu lỡ sau này biến product này lớn, nhiều field nhiều cấp thì app mình có nên dùng redux để handle action để set state ko m.

2024-06-07 02:57 UTC, huynamboz commented on app/screens/DemoCreateProductScreen.tsx
> +        });
k cần thiết lắm m

2024-06-07 02:58 UTC, huynamboz commented on app/screens/DemoCreateProductScreen.tsx
>            console.error("Error fetching categories:", error);
done

2024-06-07 02:58 UTC, huynamboz commented on app/services/module/shared.ts
> +import { api } from "../api";
done

2024-06-07 03:01 UTC, huynamboz commented on app/components/Dropdown.tsx
>            <AntDesign style={$icon} color={isFocus ? "blue" : "black"} name="Safety" size={20} />
done

2024-06-07 03:01 UTC, huynamboz commented on app/screens/DemoCreateProductScreen.tsx
> +              }}
không cần thiết lắm m, k scale tới nớ

2024-06-07 03:12 UTC, huynamboz commented on app/services/hooks/useInventory.tsx
> +  const { trigger: getCategories, isMutating } = useSWRMutation(
done

2024-06-07 06:48 UTC, huynamboz commented on app/components/CreateProduct/SelectImageGroup.tsx
> +const { v4 } = require("uuid");
done

2024-06-07 07:35 UTC, phamhongphuc1403 commented on app/components/CreateProduct/SelectImageGroup.tsx
> +    });
này dùng filter clean hơn k

2024-06-07 07:35 UTC, phamhongphuc1403 commented on app/components/CreateProduct/SelectImageGroup.tsx
> +    setItemType(newItems);
viết 1 hàm xài chung đi

2024-06-07 07:38 UTC, phamhongphuc1403 commented on app/components/CreateProduct/SelectImageGroup.tsx
> +const $inpField: ViewStyle = {
inputField ghi rõ ra luôn

2024-06-07 07:39 UTC, phamhongphuc1403 commented on app/screens/DemoCreateProductScreen.tsx
>      const conditions: RadioOption[] = [
radioOptions

2024-06-07 07:41 UTC, phamhongphuc1403 commented on app/screens/DemoCreateProductScreen.tsx
> +        });
dùng đi m

2024-06-07 07:42 UTC, phamhongphuc1403 commented on app/screens/DemoCreateProductScreen.tsx
> +        });
giả sử crate 1 product mất 10s thì làm sao handle loading gif m, với code như này?

2024-06-07 07:45 UTC, phamhongphuc1403 commented on app/screens/DemoCreateProductScreen.tsx
> +              }}
có, dùng zudstand đi

2024-06-07 07:47 UTC, phamhongphuc1403 commented on app/services/hooks/useInventory.tsx
> +  }
dùng onError

2024-06-07 08:01 UTC, huynamboz commented on app/screens/DemoCreateProductScreen.tsx
>      const conditions: RadioOption[] = [
RadioOption mới đúng m, RadioOption là 1 item mà

2024-06-07 08:01 UTC, huynamboz commented on app/components/CreateProduct/SelectImageGroup.tsx
> +const $inpField: ViewStyle = {
css ghi inp có nghĩa là input rồi m

2024-06-07 08:01 UTC, huynamboz commented on app/components/CreateProduct/SelectImageGroup.tsx
> +    });
map tối ưu hơn m

2024-06-07 08:54 UTC, phamhongphuc1403 commented on app/screens/DemoCreateProductScreen.tsx
>      const conditions: RadioOption[] = [
t thay no co nhieu items kia

2024-06-07 08:55 UTC, huynamboz commented on app/screens/DemoCreateProductScreen.tsx
> +              }}
này set data bình thường thôi mà m

2024-06-07 10:22 UTC, huynamboz commented on app/screens/DemoCreateProductScreen.tsx
>      const conditions: RadioOption[] = [
nhưng mà này là interface của 1 item

2024-06-07 10:22 UTC, huynamboz commented on app/screens/DemoCreateProductScreen.tsx
> +        });
handle loading sau, có thể set loading true ở đầu hàm và loading false ở cuối hàm

2024-06-07 10:22 UTC, huynamboz commented on app/services/hooks/useInventory.tsx
> +  }
done

2024-06-07 10:22 UTC, huynamboz commented on app/components/CreateProduct/SelectImageGroup.tsx
> +    setItemType(newItems);
done

2024-06-07 12:25 UTC, spartan-longnguyen approved these changes
Look nice to meet you

2024-06-08 01:41 UTC, trungdong11 approved these changes

2024-06-08 02:21 UTC, LeTatTuan approved these changes

2024-06-08 03:31 UTC, phamhongphuc1403 approved these changes

2024-06-08 03:34 UTC, merged