Feat/sbs 28 filter products screen
superbadteam/superbad-store_mobile pull request #6
Opened 2024-05-05 20:45 UTC by LeTatTuan

# Description

- Filter Products Screen
- Product Item Screen
- Filter SortBy Icon Screen
- SortBy Screen

## Type of change

- Change navivation community for test Filter Products Screen
## Screenshot
![Screenshot 2024-05-06 034039](https://github.com/superbadteam/superbad-store_mobile/assets/116786712/ae5b18a1-e00f-486a-9580-ee560ac09d5e)
![Screenshot 2024-05-06 034214](https://github.com/superbadteam/superbad-store_mobile/assets/116786712/6b54b547-a2f3-49ff-b956-23b3361466d8)

2024-05-06 04:11 UTC, phamhongphuc1403 reviewed
fix conflict

2024-05-08 03:21 UTC, duchuyyyy commented on app/screens/FilterProductsScreen/FilterSortByIconScreen.tsx
> +                    <Text>Srort By</Text>
Sai chính tả

2024-05-11 12:21 UTC, phamhongphuc1403 requested changes

2024-05-11 12:21 UTC, phamhongphuc1403 commented on app/components/ProductItem.tsx
> +                    <Text style={styles.discountAmount}>{discount}% OFF</Text>
dùng translation

2024-05-11 12:21 UTC, phamhongphuc1403 commented on app/components/ProductItem.tsx
> +const styles = StyleSheet.create({
sửa lại style convention cho giống mấy screen khác

2024-05-11 12:21 UTC, phamhongphuc1403 commented on app/components/ProductItem.tsx
> +    const { id, name, price, imageUrl, description, rating, isFavorite, discount } = props.item;
handle thêm id với description đi

2024-05-11 12:21 UTC, phamhongphuc1403 commented on app/components/ProductItem.tsx
> +        fontSize: 15,
component Text của boilerplate có props fontSize sẵn r, không bỏ vào style. Dò lại hết những prop đã được handle ở các component đi

2024-05-11 12:21 UTC, phamhongphuc1403 commented on app/components/ProductItem.tsx
> +                    <Ionicons name={isFavorite ? "heart" : "heart-outline"} size={24} color={isFavorite ? "red" : "black"} />
sao không dùng component Icon có sẵn của boilerplate mà dùng Ionicons?

2024-05-11 12:21 UTC, phamhongphuc1403 commented on app/components/ProductItem.tsx
> +            <Image
sao không dùng component AutoImage

2024-05-11 12:27 UTC, phamhongphuc1403 commented
chạy yarn lint chưa?

2024-05-17 16:24 UTC, LeTatTuan commented on app/screens/FilterProductsScreen/FilterSortByIconScreen.tsx
> +                    <Text>Srort By</Text>
đã fix chính tả

2024-05-17 16:24 UTC, LeTatTuan commented on app/components/ProductItem.tsx
> +const styles = StyleSheet.create({
đã sửa lại convention css

2024-05-17 16:25 UTC, LeTatTuan commented on app/components/ProductItem.tsx
> +        fontSize: 15,
đã fix các props theo component

2024-05-17 16:28 UTC, LeTatTuan commented on app/components/ProductItem.tsx
> +                    <Ionicons name={isFavorite ? "heart" : "heart-outline"} size={24} color={isFavorite ? "red" : "black"} />
Icon không có những image icon với icon của t dùng trong đó.

2024-05-17 16:29 UTC, LeTatTuan commented on app/components/ProductItem.tsx
> +            <Image
đã thay đổi sang component AutoImage

2024-05-18 06:59 UTC, huynamboz approved these changes

2024-05-18 07:04 UTC, huynamboz commented on app/components/ProductItem.tsx
> +    fontSize: 16,
cho vào prop

2024-05-18 12:52 UTC, LeTatTuan commented on app/components/ProductItem.tsx
> +                    <Text style={styles.discountAmount}>{discount}% OFF</Text>
đã fix translate

2024-05-18 12:53 UTC, LeTatTuan commented on app/components/ProductItem.tsx
> +    fontSize: 16,
đã đưa các prop vào component

2024-05-18 12:58 UTC, huynamboz approved these changes

2024-05-18 13:58 UTC, phamhongphuc1403 reviewed
update screenshot description + sửa lại convention MR title

2024-05-18 14:01 UTC, phamhongphuc1403 commented on app/screens/FilterProductsScreen/FilterSortByIconScreen.tsx
> +                    <Ionicons name="filter" size={20} color="#9494b8" />
color này không dùng biến color như mấy chỗ khác được hả

2024-05-18 14:09 UTC, LeTatTuan commented on app/components/ProductItem.tsx
> +    const { id, name, price, imageUrl, description, rating, isFavorite, discount } = props.item;
tạm thời chưa truyền id nên đã tạm bỏ id với description

2024-05-18 14:10 UTC, LeTatTuan commented on app/screens/FilterProductsScreen/FilterSortByIconScreen.tsx
> +                    <Ionicons name="filter" size={20} color="#9494b8" />
đã fix

2024-05-18 16:07 UTC, phamhongphuc1403 commented on app/screens/FilterProductsScreen/FilterSortByIconScreen.tsx
> +                    <Ionicons name="filter" size={20} color="#9494b8" />
đã fix đéo đâu

2024-05-18 17:11 UTC, phamhongphuc1403 approved these changes

2024-05-18 17:20 UTC, merged